"""Regenerate ``hist_*`` DuckDB views without touching other catalog SQL."""

from __future__ import annotations

import re
from pathlib import Path

import duckdb

from research.hist_etl.errors import HistEtlError

_BLOCK = re.compile(
    r"-- BEGIN research\.hist_etl\n.*?-- END research\.hist_etl\n?",
    re.DOTALL,
)
_VIEW_STMT = re.compile(
    r"CREATE\s+OR\s+REPLACE\s+VIEW\s+([A-Za-z_][A-Za-z0-9_]*)\s+AS\s+.*?;\s*",
    re.IGNORECASE | re.DOTALL,
)
_VIEW_NAME = re.compile(r"[a-z][a-z0-9_]*")
_FILE_NAME = re.compile(r"^([A-Z0-9]+)-\d{4}-\d{2}\.parquet$")
_BEGIN = "-- BEGIN research.hist_etl"
_END = "-- END research.hist_etl"


def refresh_catalog(root: Path) -> tuple[str, ...]:
    """Write ``catalog.sql`` and create or replace the generated views."""

    statements, names = render_statements(root)
    existing = ""
    catalog_path = root / "catalog.sql"
    if catalog_path.is_file():
        existing = catalog_path.read_text(encoding="utf-8")
    merged = merge_catalog(existing, statements, names)
    catalog_path.write_text(merged, encoding="utf-8")
    apply_catalog(root, merged)
    return names


def render_statements(root: Path) -> tuple[str, tuple[str, ...]]:
    chunks: list[str] = []
    names: list[str] = []
    binance = root / "parquet" / "binance"
    if binance.is_dir():
        for market_dir in sorted(path for path in binance.iterdir() if path.is_dir()):
            for slug_dir in sorted(path for path in market_dir.iterdir() if path.is_dir()):
                for symbol in _symbols(slug_dir):
                    relative = (
                        f"parquet/binance/{market_dir.name}/{slug_dir.name}/{symbol}-*.parquet"
                    )
                    view_names = [f"hist_bn_{market_dir.name}_{symbol.lower()}_{slug_dir.name}"]
                    if symbol == "BTCUSDT":
                        view_names.append(f"hist_bn_{market_dir.name}_{slug_dir.name}")
                    for name in view_names:
                        chunks.append(_view(name, relative))
                        names.append(name)
    kraken = root / "parquet" / "kraken" / "ohlcvt"
    if kraken.is_dir():
        for pair_dir in sorted(path for path in kraken.iterdir() if path.is_dir()):
            for interval_dir in sorted(path for path in pair_dir.iterdir() if path.is_dir()):
                if not any(interval_dir.glob("*.parquet")):
                    continue
                relative = f"parquet/kraken/ohlcvt/{pair_dir.name}/{interval_dir.name}/*.parquet"
                name = f"hist_kr_{pair_dir.name.lower()}_{interval_dir.name}"
                chunks.append(_view(name, relative))
                names.append(name)
    return "".join(chunks), tuple(names)


def merge_catalog(existing: str, statements: str, names: tuple[str, ...]) -> str:
    without_block = _BLOCK.sub("", existing)
    stripped_views = _strip_views(without_block, set(names))
    body = (
        f"{_BEGIN}\n"
        "-- Generated by python -m research.hist_etl. Do not edit inside this block.\n"
        f"{statements if statements else '-- No parquet files yet.\n'}"
        f"{_END}\n"
    )
    prefix = stripped_views.rstrip()
    if prefix:
        return prefix + "\n\n" + body
    return body


def apply_catalog(root: Path, catalog_sql: str) -> None:
    match = _BLOCK.search(catalog_sql)
    if match is None:
        raise HistEtlError("catalog.sql is missing the hist_etl block", exit_code=2)
    rendered = match.group(0).replace("__HIST__", _sql_root(root))
    database = root / "research.duckdb"
    connection = duckdb.connect(str(database))
    try:
        connection.execute("SET TimeZone='UTC'")
        for statement in _statements(rendered):
            connection.execute(statement)
    finally:
        connection.close()


def _symbols(directory: Path) -> tuple[str, ...]:
    found: set[str] = set()
    for path in directory.glob("*.parquet"):
        match = _FILE_NAME.fullmatch(path.name)
        if match is not None:
            found.add(match.group(1))
    return tuple(sorted(found))


def _view(name: str, relative_glob: str) -> str:
    if not _VIEW_NAME.fullmatch(name):
        raise HistEtlError(f"unsafe view name {name}", exit_code=2)
    if "'" in relative_glob or ".." in relative_glob.split("/"):
        raise HistEtlError(f"unsafe parquet glob {relative_glob}", exit_code=2)
    return (
        f"CREATE OR REPLACE VIEW {name} AS\n"
        f"SELECT * FROM read_parquet('__HIST__/{relative_glob}');\n"
    )


def _strip_views(sql: str, names: set[str]) -> str:
    def replace(match: re.Match[str]) -> str:
        if match.group(1) in names:
            return ""
        return match.group(0)

    return _VIEW_STMT.sub(replace, sql)


def _statements(block: str) -> list[str]:
    statements: list[str] = []
    for chunk in block.split(";"):
        lines = [
            line
            for line in chunk.splitlines()
            if line.strip() and not line.strip().startswith("--")
        ]
        statement = "\n".join(lines).strip()
        if statement:
            statements.append(statement)
    return statements


def _sql_root(root: Path) -> str:
    rendered = root.resolve().as_posix()
    if "'" in rendered or "\n" in rendered:
        raise HistEtlError("archive root cannot contain a single quote", exit_code=2)
    return rendered
